// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TunaPiano.Migrations
{
    [DbContext(typeof(TunaPianoDbContext))]
    partial class TunaPianoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("SongsId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("GenreSong");
                });

            modelBuilder.Entity("TunaPiano.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 77,
                            Bio = "Linda Ronstadt is one of the top-selling female rock artists of all time, and a trailblazer in successfully testing the boundaries of popular music across Rock, Pop, Latin, Folk, Country, Jazz, and Broadway.",
                            Name = "Linda Ronstadt"
                        },
                        new
                        {
                            Id = 2,
                            Age = 38,
                            Bio = "Carly Rae Jepsen is a Canadian singer-songwriter and actress.",
                            Name = "Carly Rae Jepsen"
                        },
                        new
                        {
                            Id = 3,
                            Age = 65,
                            Bio = "Kate Bush is an English singer, songwriter, record producer and dancer. In 1978, at the age of 19, she topped the UK Singles Chart for four weeks with her debut single \"Wuthering Heights\", becoming the first female artist to achieve a UK number one with a self-written song.",
                            Name = "Kate Bush"
                        },
                        new
                        {
                            Id = 4,
                            Age = 78,
                            Bio = "Dolly Rebecca Parton is an American singer-songwriter, actress, and philanthropist, known primarily for her decades-long career in country music. ",
                            Name = "Dolly Parton"
                        },
                        new
                        {
                            Id = 5,
                            Age = 48,
                            Bio = "Lauryn Noelle Hill is an American rapper, singer, songwriter, and record producer. Hill is regarded as one of the greatest rappers of all time, as well as one of the most influential musicians of her generation.",
                            Name = "Lauryn Hill"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Folk Rock"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pop"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Art Rock"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Country"
                        },
                        new
                        {
                            Id = 5,
                            Description = "R&B"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Simple Dreams",
                            ArtistId = 1,
                            Length = 357,
                            Title = "Blue Bayou"
                        },
                        new
                        {
                            Id = 2,
                            Album = "The Loneliest Time",
                            ArtistId = 2,
                            Length = 346,
                            Title = "Western Wind"
                        },
                        new
                        {
                            Id = 3,
                            Album = "Hounds of Love",
                            ArtistId = 3,
                            Length = 441,
                            Title = "The Big Sky"
                        },
                        new
                        {
                            Id = 4,
                            Album = "9 to 5 and Odd Jobs",
                            ArtistId = 4,
                            Length = 243,
                            Title = "9 to 5"
                        },
                        new
                        {
                            Id = 5,
                            Album = "The Miseducation of Lauryn Hill",
                            ArtistId = 5,
                            Length = 527,
                            Title = "Ex-Factor"
                        });
                });

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.HasOne("TunaPiano.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunaPiano.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TunaPiano.Models.Song", b =>
                {
                    b.HasOne("TunaPiano.Models.Artist", null)
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TunaPiano.Models.Artist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
